### ISSUE TITLE
 Caused by: java.lang.UnsupportedOperationException: Can't convert value at index 1 to color: type=0x5

### ISSUE THREAD

**Issue by chetan1011** [namito/TagCloudLinkView#5]
I got this error in my android studios 3.0 with gradle:3.0.1... before version working fine..

System.err: Caused by: java.lang.UnsupportedOperationException: Can't convert value at index 1 to color: type=0x5
at android.content.res.TypedArray.getColor(TypedArray.java:463)
at com.ns.developer.tagview.widget.TagCloudLinkView.initialize(TagCloudLinkView.java:137)
at com.ns.developer.tagview.widget.TagCloudLinkView.<init>(TagCloudLinkView.java:99)

**Comment by fabiolee** [comment]
This error is gone after I upgrade the lib project to gradle:3.0.1
The detail of the changes can be found here -> https://github.com/fabiolee/TagCloudLinkView/commit/c5995773d518204b76432e78c47a876b021f50d4

**Comment by atumRevluetion** [comment]
Same Problem! Bullshit!
